### ISSUE TITLE
[Questions] Please set an option under the player to enable/disable the video and only play the audio(to save some 4Gs)

### ISSUE THREAD

**Issue by olivertzeng** [arichorn/uYouPlusExtra#122]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Title

### Additional context

no

**Comment by xhfpsxm** [comment]
You can save data by playing in background. I recommend to disable YouPiP or disable YouPiP for mini player in settings.

**Comment by olivertzeng** [comment]
Didn't know playing in background works! Thanks!
