### ISSUE TITLE
[Questions] Community posts for iPads?

### ISSUE THREAD

**Issue by Hex34568** [arichorn/uYouPlusExtra#124]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Can you guys make it so that community posts appear on the homepage just like on Windows I saw this happening when I was tinkering with the spoofing options they showed up for a while then disappeared after i relaunched the application.So uhh it would be really nice if you guys could add an option to enable community posts on iPads

**Comment by Hex34568** [comment]
> Go to `Settings > General > Hide Community Posts` tick it to off. I apologize that this custom option is on by default. And it’s also the reason for why it isn’t showing up  

Well, thats not really the case here if you didn't know YouTube never really implemented community posts on iPads so i was looking for A/B config to enable them just like on desktops

**Comment by PoopieInMyIceCream** [comment]
@Hex34568 community posts supports ipad officially now. but there's a lot of issues when seeing them with youplusextra rn #131

**Comment by Hex34568** [comment]
> @Hex34568 community posts supports ipad officially now. but there's a lot of issues when seeing them with youplusextra rn #131

i see
