### ISSUE TITLE
[Questions] source file for sideload?

### ISSUE THREAD

**Issue by bachig26** [arichorn/uYouPlusExtra#15]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

can you make an source file to use it for AltStore and SideStore to it as an source in them?

in the readme, it's all about qnblackcat's source and it would be nice to have a source for [uYouPlusExtra](https://github.com/arichorn/uYouPlusExtra)

**Comment by arichorn** [comment]
https://tinyurl.com/28xf9b4p here’s this, one of the stable releases of uYouPlusExtra

**Comment by bachig26** [comment]
> https://tinyurl.com/28xf9b4p here’s this, one of the stable releases of uYouPlusExtra

the link is not working and shows `unsupported URL` when I add the link as Source.

**Comment by arichorn** [comment]
Sorry for my lack of response but here’s a better way.

`altstore://install?url=https://github.com/arichorn/uYouPlusExtra/releases/download/v18.05.2-2.3.1/uYouPlusExtra_18.05.2_2.3.1.ipa` copy this url and paste it onto safari and it’ll directly take you to AltStore and then it’ll start downloading the ipa.
