### ISSUE TITLE
[Q] I want to know how to update without redownloading ipa

### ISSUE THREAD

**Issue by xhfpsxm** [arichorn/uYouPlusExtra#37]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

When I used uYouPlus I didn't download new ipa every time to update to a newer version. But now I'm using uYouPlusExtra and I need to download a new ipa to use the new version. What should I do?

**Comment by xhfpsxm** [comment]
> 
Thank you for your help. I added qnblackcat's address(https://qnblackcat.github.io/AltStore/apps.json) to source when using uyouplus. I wonder if this has something to do with why it was able to update. If so, I would like to add your address to the source.

**Comment by xhfpsxm** [comment]
>

Thank you for your help. I added qnblackcat's address(https://qnblackcat.github.io/AltStore/apps.json) to source when using uyouplus. I wonder if this has something to do with why it was able to update. If so, I would like to add your address to the source.

**Comment by xhfpsxm** [comment]
>
That's what I want. Thank you very much.

**Comment by mahyess** [comment]
Not sure if I should create a new issue for this, but trying to add "uYoutPlusExtra Source" to AltStore results in an error `The source "uYouPlusExtra Source" is not supported by this version of AltStore.`

AltStore Version: 1.7

**Comment by yodaluca23** [comment]
> Not sure if I should create a new issue for this, but trying to add "uYoutPlusExtra Source" to AltStore results in an error `The source "uYouPlusExtra Source" is not supported by this version of AltStore.`
> 
> 
> 
> AltStore Version: 1.7

Well that's your problem, why are you not on the beta? Add [this](https://quarksources.github.io/dist/altstore-complete.min.json) source, then download and install Altstore (Beta).
