### ISSUE TITLE
[Bug] PiP button crashes app

### ISSUE THREAD

**Issue by MarioMastr** [arichorn/uYouPlusExtra#4]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iOS 16.1 DB5
- Device model: 11
- Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...): AltStore 
- The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_ 17.41.2-2.1 Extra

### Describe the bug
YouPIP video player button crashes the app

### How to reproduce the bug
1. Turn on video player button in YouPIP settings
2. Try to go into PiP in a video using said button

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why?
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_
Yeah
### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_

### Additional context: 
I assume iOS 16.1 beta 6 is going to release later today, so I'm going to come back and update you on the situation after I update to that.

**Comment by arichorn** [comment]
@MarioMastr I was one step ahead of this post, and yeah I know it’s crashing I will release a newer version later today!

**Comment by arichorn** [comment]
https://github.com/arichorn/uYouPlusExtra/releases 👍 here you go! This release should fix it
