### ISSUE TITLE
[Bug] Community Posts Disappearing

### ISSUE THREAD

**Issue by MJF027** [arichorn/uYouPlusExtra#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Select uYou Label

- [X] uYou

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 16.5.1 (c)
- Device model: iPhone SE 2nd Gen
- Sideload tool (AltStore, Sideloadly, TrollStore,...): AltStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): v3.0

### Describe the bug

Community posts disappear, regardless if I access them under Subscriptions or from the Community tab on a channel.

### Steps to reproduce the issue

1. Scroll through Subscriptions. 
2. Videos appear but community posts disappear.
3. Open Community tab from a channel.
4. Upon scrolling, community posts disappear with a blank white screen under the tab.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by BatSmacker84** [comment]
This is an intended feature, first added with the v18.27.3-3.0 release. 

If you want to disable the feature, go to the General YouTube settings and scroll to the bottom. Toggle the "Show Community Posts" to on and they will show up once again.

**Comment by MJF027** [comment]
Thanks, that did it! The actual YouTube app v18.28.3 doesn’t have that setting, so I didn’t think to check that.
