### ISSUE TITLE
[Bug] Playlists/Podcasts break with OLED & Old Dark Mode Themes

### ISSUE THREAD

**Issue by PoopieInMyIceCream** [arichorn/uYouPlusExtra#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 15.6.1
- Device model: iPad (7th Gen)
- Sideload tool: [AppDB](https://appdb.to) (via downloading custom application on [MyAppStore](https://appdb.to/my/store))
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): [v18.30.6-3.0.1](https://github.com/arichorn/uYouPlusExtra/releases/tag/v18.30.6-3.0.1)

### Describe the bug

OLED Theme breaks yt playlist:
![OLED-Break-YT_Playlist](https://github.com/arichorn/uYouPlusExtra/assets/119268684/79d5a9e2-5a17-4331-95e6-d68e7ab149a5)
#
Same with Old Dark Mode:
![044C4B1C-02EE-4D36-B1FE-058DF7CE93C5](https://github.com/arichorn/uYouPlusExtra/assets/119268684/20b67e3d-2c61-4bbb-b933-b0dbcbdf933f)
#
what a normal playlist looks like:
![NormalYT-Playlist](https://github.com/arichorn/uYouPlusExtra/assets/119268684/234dfe08-7628-4295-a10c-162675ddd7ce)

### Steps to reproduce the issue

1. Turn on OLED/Old Dark Mode Theme in youplus theme settings
2. Go see any youtube playlist/podcast

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Playlists/Podcasts show correctly when using the default dark mode theme

**Comment by OasisOiger** [comment]
updated bug report with my new findings that Old Dark Mode also breaks playlists

**Comment by OasisOiger** [comment]
@arichorn dont think so, i havent touched the a/b flags when i first made this bug report on [v18.30.6-3.0.1](https://github.com/arichorn/uYouPlusExtra/releases/tag/v18.30.6-3.0.1)

**Comment by PoopieInMyIceCream** [comment]
@arichorn OLED theme now works with playlists and podcasts
