### ISSUE TITLE
[Bug] Library/You Tab Breaks when its Reordered Far Left of Tab While Hiding uYou Tab

### ISSUE THREAD

**Issue by PoopieInMyIceCream** [arichorn/uYouPlusExtra#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Select uYou Label

- [X] uYou

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 15.6.1
- Device model: iPad (7th Gen)
- Sideload tool: [AppDB](https://appdb.to) (via downloading custom application on [MyAppStore](https://appdb.to/my/store))
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): [v18.30.6-3.0.1](https://github.com/arichorn/uYouPlusExtra/releases/tag/v18.30.6-3.0.1)

### Describe the bug

Library tab works with uYou tab
![B873A7D2-74EA-4E5C-AE21-4F638EE5569F](https://github.com/arichorn/uYouPlusExtra/assets/119268684/9f414d50-c3bf-41ba-b6ee-b5bacd08594e)
#
Library tab doesn't work without uYou tab (NOTE: this bug always happens when you move library tab to far left side of bottom tab)
![D81FDA99-5410-4282-A75C-707AE1B5ADBA](https://github.com/arichorn/uYouPlusExtra/assets/119268684/07807444-424e-44a6-a240-b0e551532d0d)

### Steps to reproduce the issue

1. Reorder Library tab to the far left tab in uYou "Reorder Tabs" setting
2. Hide uYou in uYou "Hide Tabs" setting
3. Restart Youtube to see the changes

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

This bug only happens when you reorder library tab to the left of home tab
#
library perfectly works to the right of home without uYou
![1760E134-0554-430B-ACA9-9470C8A666F6](https://github.com/arichorn/uYouPlusExtra/assets/119268684/52b27c88-328b-4092-9fc9-a010fe4c8461)

**Comment by OasisOiger** [comment]
@arichorn i believe it is a uYou issue. as when I used the original youplus ver. by blackcat, i experienced the same reordering issue in uYoun

**Comment by OasisOiger** [comment]
@arichorn i did not turn on/off any a/b setting directly. this issue happens when you move the library to the left of home and hide uYou tab

**Comment by OasisOiger** [comment]
@arichorn also after some testing. the library tab **always breaks** when its on the far left side of the bar without uYou tab (will update initial post with my findings)
![4A75559A-AB64-4EF5-B72A-5314A5E1FCA7](https://github.com/arichorn/uYouPlusExtra/assets/119268684/a8e27326-eec2-4f63-a6aa-1cf280fdcf2f)

**Comment by OasisOiger** [comment]
subscription tabs is actually fine without uYou
![3C165043-FA03-4E7C-AB9F-5B3142008705](https://github.com/arichorn/uYouPlusExtra/assets/119268684/ebbe2852-5721-4b09-8b4d-f74ab6e7ce17)

**Comment by OasisOiger** [comment]
oh well guess the bug is inconsistent on any devices, either way hope someone checks that out

**Comment by PoopieInMyIceCream** [comment]
@arichorn just checked this bug again, and the bug is fixed for both library and you tab now
